// lib/uz-latn.ts — hand-built Uzbek (Latin) locale packs (02-design-language.md §7):
// an AntD v6 Locale (~40 strings) and a minimal dayjs locale (weekStart 1,
// L = DD.MM.YYYY). The ru_RU ConfigProvider dies.
import type { Locale } from 'antd/es/locale';

const weekdays = [
  'Yakshanba',
  'Dushanba',
  'Seshanba',
  'Chorshanba',
  'Payshanba',
  'Juma',
  'Shanba',
];
const weekdaysShort = ['Yak', 'Dush', 'Sesh', 'Chor', 'Pay', 'Jum', 'Shan'];
const weekdaysMin = ['Ya', 'Du', 'Se', 'Cho', 'Pa', 'Ju', 'Sha'];
const months = [
  'Yanvar',
  'Fevral',
  'Mart',
  'Aprel',
  'May',
  'Iyun',
  'Iyul',
  'Avgust',
  'Sentabr',
  'Oktabr',
  'Noyabr',
  'Dekabr',
];
const monthsShort = [
  'Yan',
  'Fev',
  'Mar',
  'Apr',
  'May',
  'Iyn',
  'Iyl',
  'Avg',
  'Sen',
  'Okt',
  'Noy',
  'Dek',
];

// dayjs locale — registered globally in main.tsx via dayjs.locale(dayjsUzLatn).
export const dayjsUzLatn: ILocale = {
  name: 'uz-latn',
  weekdays,
  weekdaysShort,
  weekdaysMin,
  months,
  monthsShort,
  weekStart: 1,
  ordinal: (n: number) => n,
  formats: {
    LT: 'HH:mm',
    LTS: 'HH:mm:ss',
    L: 'DD.MM.YYYY',
    LL: 'D MMMM YYYY',
    LLL: 'DD.MM.YYYY HH:mm',
    LLLL: 'D MMMM YYYY, dddd, HH:mm',
  },
  relativeTime: {
    future: '%s ichida',
    past: '%s oldin',
    s: 'bir necha soniya',
    m: 'bir daqiqa',
    mm: '%d daqiqa',
    h: 'bir soat',
    hh: '%d soat',
    d: 'bir kun',
    dd: '%d kun',
    M: 'bir oy',
    MM: '%d oy',
    y: 'bir yil',
    yy: '%d yil',
  },
};

// AntD DatePicker/Calendar share one picker locale.
// lang.locale 'uz-latn' resolves to the dayjs locale registered above.
const pickerLocale = {
  lang: {
    locale: 'uz-latn',
    placeholder: 'Sanani tanlang',
    yearPlaceholder: 'Yilni tanlang',
    quarterPlaceholder: 'Chorakni tanlang',
    monthPlaceholder: 'Oyni tanlang',
    weekPlaceholder: 'Haftani tanlang',
    rangePlaceholder: ['Boshlanish sanasi', 'Tugash sanasi'] as [string, string],
    rangeYearPlaceholder: ['Boshlanish yili', 'Tugash yili'] as [string, string],
    rangeMonthPlaceholder: ['Boshlanish oyi', 'Tugash oyi'] as [string, string],
    rangeWeekPlaceholder: ['Boshlanish haftasi', 'Tugash haftasi'] as [string, string],
    shortWeekDays: weekdaysMin,
    shortMonths: monthsShort,
    fieldDateFormat: 'DD.MM.YYYY',
    fieldDateTimeFormat: 'DD.MM.YYYY HH:mm',
    fieldMonthFormat: 'MM.YYYY',
    fieldYearFormat: 'YYYY',
    yearFormat: 'YYYY',
    cellDateFormat: 'D',
    monthBeforeYear: true,
    today: 'Bugun',
    now: 'Hozir',
    backToToday: 'Bugunga qaytish',
    ok: 'OK',
    clear: 'Tozalash',
    week: 'Hafta',
    month: 'Oy',
    year: 'Yil',
    timeSelect: 'Vaqtni tanlash',
    dateSelect: 'Sanani tanlash',
    weekSelect: 'Haftani tanlash',
    monthSelect: 'Oyni tanlash',
    yearSelect: 'Yilni tanlash',
    decadeSelect: "O'n yillikni tanlash",
    previousMonth: 'Oldingi oy (PageUp)',
    nextMonth: 'Keyingi oy (PageDown)',
    previousYear: 'Oldingi yil (Ctrl + chap)',
    nextYear: "Keyingi yil (Ctrl + o'ng)",
    previousDecade: "Oldingi o'n yillik",
    nextDecade: "Keyingi o'n yillik",
    previousCentury: 'Oldingi asr',
    nextCentury: 'Keyingi asr',
  },
  timePickerLocale: {
    placeholder: 'Vaqtni tanlang',
    rangePlaceholder: ['Boshlanish vaqti', 'Tugash vaqti'] as [string, string],
  },
};

export const uzLatn: Locale = {
  locale: 'uz-latn',
  Pagination: {
    items_per_page: '/ sahifa',
    jump_to: "O'tish",
    jump_to_confirm: 'tasdiqlash',
    page: 'Sahifa',
    prev_page: 'Oldingi sahifa',
    next_page: 'Keyingi sahifa',
    prev_5: 'Oldingi 5 sahifa',
    next_5: 'Keyingi 5 sahifa',
    prev_3: 'Oldingi 3 sahifa',
    next_3: 'Keyingi 3 sahifa',
    page_size: 'Sahifa hajmi',
  },
  DatePicker: pickerLocale,
  Calendar: pickerLocale,
  TimePicker: pickerLocale.timePickerLocale,
  Table: {
    filterTitle: 'Filtr',
    filterConfirm: 'OK',
    filterReset: 'Tozalash',
    filterEmptyText: "Filtr yo'q",
    filterCheckAll: 'Hammasini tanlash',
    filterSearchPlaceholder: 'Filtrda qidirish',
    emptyText: "Ma'lumot yo'q",
    selectAll: 'Joriy sahifani tanlash',
    selectInvert: 'Tanlovni teskarisiga aylantirish',
    selectNone: 'Tanlovni tozalash',
    selectionAll: 'Hammasini tanlash',
    sortTitle: 'Saralash',
    expand: 'Qatorni ochish',
    collapse: 'Qatorni yopish',
    triggerDesc: "Kamayish bo'yicha saralash",
    triggerAsc: "O'sish bo'yicha saralash",
    cancelSort: 'Saralashni bekor qilish',
  },
  Modal: {
    okText: 'OK',
    cancelText: 'Bekor',
    justOkText: 'OK',
  },
  Popconfirm: {
    okText: 'OK',
    cancelText: 'Bekor',
  },
  Select: {
    notFoundContent: "Ma'lumot yo'q",
  },
  Empty: {
    description: "Ma'lumot yo'q",
  },
  Upload: {
    uploading: 'Yuklanmoqda…',
    removeFile: 'Faylni olib tashlash',
    uploadError: 'Yuklashda xatolik',
    previewFile: "Faylni ko'rish",
    downloadFile: 'Faylni yuklab olish',
  },
  global: {
    placeholder: 'Tanlang',
    close: 'Yopish',
  },
};
